# Generated by Django 5.1.4 on 2025-03-05 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='blog_id',
        ),
    ]
