# Generated by Django 5.1.4 on 2025-03-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_rename_blog_comment_blog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('White', 'White'), ('Grey', 'Grey')], default='Red', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('SizeS', 'SizeS'), ('SizeM', 'SizeM'), ('SizeL', 'SizeL'), ('SizeXL', 'SizeXL')], default='SizeS', max_length=200),
        ),
    ]
