# Generated by Django 5.1.4 on 2025-03-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_product_color_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
