# Generated by Django 5.1.4 on 2025-03-11 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
