# Generated by Django 5.1.4 on 2025-03-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_alter_rating_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
