# Generated by Django 5.1.4 on 2025-03-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='txnid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
