# Generated by Django 5.1.4 on 2025-03-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_cartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='image1',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
