# Generated by Django 5.2 on 2025-05-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_alter_cartitem_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
