# Generated by Django 5.2 on 2025-05-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
