# Generated by Django 5.2 on 2025-05-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_orderitem_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='payment_id',
            new_name='number',
        ),
    ]
